---
title: "Practice with Dataframes"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r}
dfPatient=read.csv('Data/emergency.csv')
str(dfPatient)
```

```{r}
dfPatient$Condition
str(dfPatient$Condition) #chr
```

```{r}
dfPatient[['Condition']] #same as used in $
```

```{r}
dfPatient['Condition']
str(dfPatient['Condition']) #dataframe
```

```{r}
dfPatient[1] #can access column in dataframe
```

```{r}
dfPatient[,'Condition']
```

```{r}
dfPatient$Condition #vector
dfPatient[['Condition']] #vector
dfPatient['Condition'] #dataframe
dfPatient[2] #dataframe
dfPatient[,'Condition'] #vector
#check using str ()-all above are used to access data from Condition

```

```{r}
dfPatient$Condition=='serious' #boolean vector
```

```{r}
dfPatient[3,]
```

```{r}
dfPatient[dfPatient$Condition=='serious',] #dataframe
str(dfPatient[dfPatient$Condition=='serious',])
```

```{r}
sum(dfPatient$Condition=='serious') #return sum
mean(dfPatient$Condition=='serious') #average if percentage thn *100
```

```{r}
mean(dfPatient$Insurance=='not insured')
sum(dfPatient$Insurance=='not insured')
```


```{r}
dfPatient=read.csv('Data/emergency.csv',row.names=1, stringsAsFactors = TRUE)
str(dfPatient)
```

```{r}
dfPatient=read.csv('Data/emergency.csv',row.names=1)
str(dfPatient)
```

```{r}
dfPatient$Condition=factor(dfPatient$Condition)
str(dfPatient)
```

```{r}
dfPatient$Insurance=factor(dfPatient$Insurance)
str(dfPatient)
```

```{r}
categorical_cols=c('Condition','Insurance') #3types of categorical-binary,multilabel,ordinal
#str(categorical_cols)
lapply(dfPatient[,categorical_cols],factor)
str(lapply(dfPatient[,categorical_cols],factor))
```

```{r}
dfPatient[,categorical_cols]=lapply(dfPatient[,categorical_cols],factor)
str(dfPatient)
```

```{r}
dfPatient[dfPatient$Condition=='serious',] $Insurance=='insured'
```

```{r}
mean(dfPatient[dfPatient$Condition=='serious',] $Insurance=='insured')
```

```{r}
mean((dfPatient$Condition=='serious')&(dfPatient$Insurance=='insured'))
```

```{r}
mean((dfPatient$Condition=='serious')&(dfPatient$Insurance=='insured'))/mean(dfPatient$Insurance=='insured')
```

```{r}
mean(dfPatient[dfPatient$Insurance=='insured',]$Condition=='serious')
```

